shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from accounts import views as accountViews
from django.contrib.auth import views as auth_views #import this
from products import views as productViews
from . import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('accounts/',accountViews.accountView,name='accounts'),
    path('accounts/signup/',accountViews.signup,name='signup'),
    path('accounts/login/',accountViews.loginUser,name='login'),
    path('accounts/logout/',accountViews.logoutUser,name='logout'),
    path('activate/<uidb64>/<token>/',accountViews.activate, name='activate'),
    path('validateEmail/',accountViews.validateEmail,name='validateEmail'),
    path('validateName/',accountViews.name_validate,name='validateName'),
    path('validatePass/',accountViews.validatePass,name='validatePass',),
    path('numericPass/',accountViews.numericPass,name='numericPass',),
    path('comparePass/',accountViews.comparePass,name='comparePass',),
    path('commanPass/',accountViews.commanPassCheck,name='commanPass',),
    path('accounts/forget-password/',accountViews.forget_pass_view,name='forget-password'),
    path('accounts/forget-password-confirm/<uidb64>/<token>/',accountViews.forget_pass_comfirm_view, name='forget-password-confirm'),
    path('accounts/change-password/',accountViews.change_password,name='change-password'),
    path('page-not-found/',views.invalid_url_view,name='invalid-url'),
    re_path(r'^category/(?P<slug>.*)/$',productViews.category,name='category'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('product/<int:id>/<slug:slug>',productViews.product_detail,name="product-details"),
    path('addfavorite/<int:id>',productViews.add_to_favorite,name='add-favorite'),
    path('favorites/',productViews.view_favorites,name='your-favorites'),
    path('about-us/',views.about_view,name="about"),
    path('contact-us/',views.contact_view,name="contact"),
    path('search_auto/',views.search_auto,name="search_auto"),
    path('search/',views.search,name="search"),
    path('FAQ/',views.FAQ_View,name="faq"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.base_user import BaseUserManager


# Create your models here.

#custom user manager model
class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)

#custome user model
class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

shop/shop/models.py
from django.db import models
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField


class Contact(models.Model):
    contact_name=models.CharField(max_length=50)
    contact_email=models.EmailField(max_length=255)
    message=models.TextField()
    contacted_on=models.DateTimeField(null=True,blank=True,auto_now_add=True)

class Team(models.Model):
    Member_Name = models.CharField(blank=False,max_length=70)
    Member_Position = models.CharField(blank=False,max_length=100)
    Member_Profile = models.ImageField(blank=False,upload_to="img/")
    Member_Profile_Alternative_Text = models.CharField(blank=True,max_length=255)
    Member_FaceBook_Account = models.CharField(blank=True,max_length=255)
    Member_Twitter_Account = models.CharField(blank=True,max_length=255)
    Member_Instagram_Account = models.CharField(blank=True,max_length=255)
    Member_Linkdin_Account = models.CharField(blank=True,max_length=255)

    def image_tag(self):
        if self.Member_Profile is not None:
            return mark_safe('<img src="{}" height="50"/>'.format(self.Member_Profile.url))
        else:
            return ""
    
    def __str__(self):
        return self.Member_Name


class SiteSetting(models.Model):
    Fav_Icon = models.ImageField(upload_to='img/')
    Site_Logo = models.ImageField(upload_to='img/')
    home_page_title = models.CharField(max_length=255,blank=True)
    account_page_title = models.CharField(max_length=255,blank=True)
    forget_page_title = models.CharField(max_length=255,blank=True)
    forget_comfirm_page_title = models.CharField(max_length=255,blank=True)
    change_password_page_title = models.CharField(max_length=255,blank=True)
    about_page_title = models.CharField(max_length=255,blank=True)
    contact_page_title = models.CharField(max_length=255,blank=True)
    faq_page_title = models.CharField(max_length=255,blank=True)
    error_404_page_title = models.CharField(max_length=255,blank=True)
    favourite_list_page_title = models.CharField(max_length=255,blank=True)
    home_page_meta_description=models.TextField(null=True,blank=True)
    home_page_meta_keywords=models.TextField(null=True,blank=True)
    about_page_meta_description=models.TextField(null=True,blank=True)
    about_page_meta_keywords=models.TextField(null=True,blank=True)
    contact_page_meta_description=models.TextField(null=True,blank=True)
    contact_page_meta_keywords=models.TextField(null=True,blank=True)
    faq_page_meta_description=models.TextField(null=True,blank=True)
    faq_page_meta_keywords=models.TextField(null=True,blank=True)
    Home_Page_Banner = models.ImageField(blank=True,upload_to='img/')
    Home_Page_Banner_Alternative_Text = models.CharField(blank=True,max_length=255)
    Home_Page_Small_Text = models.CharField(blank=True,max_length=255)
    Home_Page_Big_Text = models.CharField(blank=True,max_length=255)
    FaceBook_Account = models.CharField(blank=True,max_length=255)
    Twitter_Account = models.CharField(blank=True,max_length=255)
    Instagram_Account = models.CharField(blank=True,max_length=255)
    Linkedin_Account = models.CharField(blank=True,max_length=255)
    Address = models.CharField(blank=True,max_length=255)
    Contact_No_1 = models.CharField(blank=True,max_length=255)
    Contact_No_2 = models.CharField(blank=True,max_length=255)
    Email = models.EmailField(blank=True,max_length=255)
    Short_About_Us = models.TextField(blank=True)
    About_Us_Image = models.ImageField(blank=True,upload_to='img/')
    About_Us_Image_Alternative_Text = models.CharField(blank=True,max_length=255)
    About_Us = RichTextUploadingField()
    Our_Mission_Image = models.ImageField(blank=True,upload_to='img/')
    Our_Mission_Image_Alternative_Text = models.CharField(blank=True,max_length=255)
    Our_Mission = RichTextUploadingField()

    def fav_icon_image_tag(self):
        if self.Fav_Icon is not None:
            return mark_safe('<img src="{}" height="50"/>'.format(self.Fav_Icon.url))
        else:
            return ""
    
    def logo_image_tag(self):
        if self.Site_Logo is not None:
            return mark_safe('<img src="{}" height="50"/>'.format(self.Site_Logo.url))
        else:
            return ""

class FAQ(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    position_number = models.IntegerField()
    question = models.CharField(max_length=200)
    answer = RichTextUploadingField()
    status=models.CharField(max_length=10, choices=STATUS)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

shop/accounts/forms.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from .models import CustomUser


#register from specified here with custom fields
class RegisterForm(UserCreationForm):
    email=forms.EmailField(required=True,help_text="Ex. xyz@abc.com",widget=forms.EmailInput(attrs={'class':'common-input mt-20'}))
    password1=forms.CharField(required=True,help_text='',label="Password",widget=forms.PasswordInput(attrs={'class':'common-input'}))
    password2=forms.CharField(required=True,help_text='',label="Password Confirmation",widget=forms.PasswordInput(attrs={'class':'common-input mt-20'}))
    class Meta:
        model=CustomUser
        fields=['email','password1','password2']

shop/shop/forms.py
from django.core.validators import RegexValidator
from django import forms
from .models import Contact


alphabet_validate=RegexValidator(r'[A-Za-z]+',"Name must be in aphabets only.")
class ContactForm(forms.ModelForm):
    contact_name=forms.CharField(required=True,widget=forms.PasswordInput(attrs={'class':'common-input mt-20'}),validators=[alphabet_validate])
    class Meta:
        model=Contact
        fields=['contact_name','contact_email','message']

shop/templates/FAQ.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load mptt_tags %}
{% load env_extras %}

{% block meta_tags %}
    <!-- Author Meta -->
    <meta name="author" content="">
    <!-- Meta Description -->
    <meta name="description" content="{% get_site_setting as site %}{{ site.faq_page_meta_description }}">
    <!-- Meta Keyword -->
    <meta name="keywords" content="{% get_site_setting as site %}{{ site.faq_page_meta_keywords }}">
{% endblock %}

{% block title_tag %}{% get_site_setting as site %}{{ site.faq_page_title }}{% endblock %}

{% block custom_css_and_links %}
{% endblock %}

{% block breadcrum %}
<section class="banner-area organic-breadcrumb">
    <div class="container mt-lg-0 mt-md-120 mt-120 mt-sm-200">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center">
            <div class="col-lg-12 col-xs-12 col-first col-sm-12 d-flex flex-wrap align-items-center">
                <a href="{% url 'home'%}">Home&nbsp;&nbsp;<i class="fa fa-caret-right" aria-hidden="true"></i>&nbsp;</a>
                <a href="{% url 'faq'%}">Frequently Asked Questions</a>
            </div>
        </div>
    </div>
  </section>
{% endblock %}

{% block content %}

<div class="container mb-5 ">
    <div class="container">
        <h1 class="title faqtitle">Frequently Asked Questions</h1>
        <div id="accordion" class="accordion mt-4">
            <div class="card mb-0">
                {% for rs in faq %}
                <div class="card-header collapsed" data-toggle="collapse" href="#{{rs.position_number}}">
                    <a class="card-title">
                        Q.&nbsp;&nbsp;{{ rs.question }}
                    </a>
                </div>
                <div id="{{rs.position_number}}" class="card-body collapse" data-parent="#accordion" >
                    <p>
                        Answer:&nbsp;&nbsp;{{ rs.answer | safe }}
                    </p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block scripts %}
{% endblock %}

shop/templates/accounts.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load env_extras %}
{% block meta_tags %}

{% endblock %}

{% block title_tag %}{% get_site_setting as site %}{{ site.account_page_title }}{% endblock %}

{% block custom_css_and_links %}

{% endblock %}

{% block breadcrum %}
<section class="banner-area organic-breadcrumb">
  <div class="container mt-lg-0 mt-md-120 mt-120 mt-sm-200">
      <div class="breadcrumb-banner d-flex flex-wrap align-items-center">
          <div class="col-lg-12 col-xs-12 col-first col-sm-12 d-flex flex-wrap align-items-center">
              <a href="{% url 'home'%}">Home&nbsp;&nbsp;<i class="fa fa-caret-right" aria-hidden="true"></i>&nbsp;</a>
              <a href="{% url 'accounts'%}">Accounts</a>
          </div>
      </div>
  </div>
</section>
{% endblock %}

{% block content %}
<div class="container">
  <div class="container">
    <div class="row success-messages">
      {% if messages %}
        {% for message in messages %}
          {% if  message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <span class="text-center"><i class="fa fa-check-circle-o" aria-hidden="true"></i>&nbsp;&nbsp;{{message}}</span>
          {% endif %}
        {% endfor %}
      {% endif %}
    </div>
  </div>
  <div class="row account-form">
    <div class="col-md-6">
      <div class="login-form">
        <h3 class="billing-title text-center">Login</h3>
        <p class="text-center mt-40 mb-40 account-sub-title">Welcome back! Sign in to your account </p>
        <form action="{% url 'login' %}" method="POST">
          {% csrf_token %}
          <label for="email">Email <span class="error">*</span></label>
          {% if otp_send_mail %}
            {{otp_send_mail}} <a href="{% url 'accounts'%}">Change Email</a>
            <input type="hidden" id="email" name="email" value="{{otp_send_mail}}" required class="common-input mt-20">
            <br/>
          {% else %}
            <input type="email" id="email" name="email" placeholder="Enter your email*" onfocus="this.placeholder=''" onblur="this.placeholder = 'Enter your email*'" required class="common-input mt-20">
          {% endif %}
          <span class="error" id="email_error">
            {% if email_error %}
              {{email_error}}
            {% endif %}
            {% if user_not_exsist %}
              {{user_not_exsist}}
            {% endif %}
          </span>
          <br/><br/>
          {% if otp_send_mail %}
          {% else %}
          <label for="password">Password <span class="error">*</span></label>
          <div class="passtrengthMeter login_pass">
            <input type="password" id="password" name="password" placeholder="Enter your password*" onfocus="this.placeholder=''" onblur="this.placeholder = 'Enter your password*'"  class="common-input mt-20">
            <a href=""><span class="showPassword">
              <img src="/media/img/eye.svg">
            </span></a>
          </div>
          {% endif %}
          {% if otp_send_mail %}
          <label for="otp">Login Code <span class="error">*</span></label>
          <input type="text" id="otp" name="otp" placeholder="Enter your Login code*" onfocus="this.placeholder=''" onblur="this.placeholder = 'Enter your Login code*'"  class="common-input mt-20">
          <span class="help-text">Login code wich have been sent on your given email address.</span>
          <br/>
          {% endif %}
          <span class="error">
            {% if password_or_otp_error %}
              {{password_or_otp_error}}
            {% endif %}
            {% if invalid_creds_error %}
              {{invalid_creds_error}}
            {% endif %}
          </span>
          <span class="success">
            {% if resend_code_sent %}
              <i class="fa fa-check-circle-o" aria-hidden="true"></i>&nbsp;&nbsp;{{resend_code_sent}}
            {% endif %}
          </span>
          <br/><br/>
          <button class="view-btn color-2 mt-20 w-100" name='login' value="login">
              <span>Login
              </span>
          </button>
          {% if otp_send_mail %}
             <button class="view-btn color-2 mt-20 w-100" name='resendcode' value="resendcode"><span>Resend Login Code</span></button>
             <a href="" class="d-flex justify-content-center align-items-center mt-20">Back to login with password</a>
          {% else %}
          <button class="view-btn color-2 mt-20 w-100" name='otplogin' value="otplogin"><span>Request Login Code</span></button>
          <div class="mt-20 d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center"><input type="checkbox" class="pixel-checkbox" id="remember_me" name="remember_me">
            <label for="login-1">Keep me logged in.</label></div>
            <a href="{% url 'forget-password' %}">Forget your password?</a>
          </div>
          {% endif %}
        </form>
      </div>
    </div>
    <div class="col-md-6">
      <div class="login-form">
        <h3 class="billing-title text-center">Register</h3>
        <p class="text-center mt-40 mb-30 account-sub-title">Create your very own account </p>
        <form action="{% url 'signup' %}" method="POST">  
          {% csrf_token %}
          {% for field in form %}
              <label for="{{ field.name }}">{{ field.label }} <span class="error">*</span></label>
              
              {% ifequal field.name 'email' %}
                {{ field }}
                <span class="error" id="reg_email_error"></span>
              {% endifequal %}
              {% ifequal field.name 'password1' %}
              <div class="passtrengthMeter pass">
                <input type="password" name="password1" class="common-input" required="" id="id_password1">
                <a href=""><span class="showPassword">
                  <img src="/media/img/eye.svg">
                </span></a>
              </div>
              {% endifequal %}
              {% ifequal field.name 'password2' %}
                <div class="passtrengthMeter re_pass">
                  <input type="password" name="password2" class="common-input" required="" id="id_password2">
                  <a href=""><span class="showPassword">
                    <img src="/media/img/eye.svg">
                  </span></a>
                </div>
              {% endifequal %}
              <p class="help-text">{{ field.help_text }} </p>
              {% for error in field.errors %}
                <span class="error" id="field_errors">{{ error }}</span><br/>
              {% endfor %}
          {% endfor %}
          <span class="error" id="pass_error"></span>
          <span class="error" id="comman_pass_error"></span>
          <span class="error" id="numeric_pass_error"></span>
          <span class="error" id="confirm_pass_error"></span>
          <button type="submit" class="view-btn color-2 mt-20 w-100"><span>Register</span></button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}


{% block scripts %}
<script src="{% static 'js/accounts.js' %}"></script> 
<script>
  validate_email("#email","#email_error");//login email
  validate_email("#id_email","#reg_email_error");//registration email
  password_check("#id_password1","#id_password2");// all email
  //pass show and strength pulgin
  $(document).ready(function($) {
    $('#id_password1').passtrength({
      minChars:8,
      passwordToggle: false,
      tooltip: true,
    });
  });
  $(document).ready(function() {
    showPass_func('re_pass',"#id_password2");
  });
  $(document).ready(function() {
    showPass_func('pass',"#id_password1");
  });
  $(document).ready(function() {
    showPass_func('login_pass',"#password");
  });
</script>
{% endblock %}

shop/templates/contact_us.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load mptt_tags %}
{% load env_extras %}

{% block meta_tags %}
    <!-- Author Meta -->
    <meta name="author" content="">
    <!-- Meta Description -->
    <meta name="description" content="{% get_site_setting as site %}{{ site.contact_page_meta_description }}">
    <!-- Meta Keyword -->
    <meta name="keywords" content="{% get_site_setting as site %}{{ site.contact_page_meta_keywords }}">
{% endblock %}

{% block title_tag %}{% get_site_setting as site %}{{ site.contact_page_title }}{% endblock %}

{% block custom_css_and_links %}
{% endblock %}

{% block breadcrum %}
<section class="banner-area organic-breadcrumb">
    <div class="container mt-lg-0 mt-md-120 mt-120 mt-sm-200">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center">
            <div class="col-lg-12 col-xs-12 col-first col-sm-12 d-flex flex-wrap align-items-center">
                <a href="{% url 'home'%}">Home&nbsp;&nbsp;<i class="fa fa-caret-right" aria-hidden="true"></i>&nbsp;</a>
                <a href="{% url 'contact'%}">Contact Us</a>
            </div>
        </div>
    </div>
  </section>
{% endblock %}

{% block content %}

<div class="container mb-5">
    <div class="container">
        <div class="row success-messages">
            {% if messages %}
            {% for message in messages %}
                {% if  message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <span class="text-center"><i class="fa fa-check-circle-o" aria-hidden="true"></i>&nbsp;&nbsp;{{message}}</span>
                {% endif %}
            {% endfor %}
            {% endif %}
        </div>
    </div>
    <div><h1>Contact Us</h1></div>
    <div class='mb-3 mt-2 contact-bottom-line banner-area'></div>
    <br />
    <div class="row">
        <div class="col-md-6 googleMapDiv">
            <div id="googlemap"></div>
        </div>
        <br />
        <div class="col-md-6">
            <form class="my-form" method="POST" action="{% url 'contact' %}">
                {% csrf_token %}
                {% for field in form %}
                    {% ifequal field.name 'contact_name' %}
                        <div class="form-group">
                            <label for="form-name">Name</label>
                            <input type="text" class="common-input" id="id_contact_name" name="contact_name" placeholder="Name">
                            <span class="error" id="contact_error"></span>
                        </div>
                    {% endifequal %}
                    {% ifequal field.name 'contact_email' %}
                    <div class="form-group">
                        <label for="form-email">Email Address</label>
                        <input type="email" class="common-input" id="id_contact_email" name="contact_email" placeholder="Email Address">
                        <span class="error" id="email_error"></span>
                    </div>
                    {% endifequal %}
                    {% ifequal field.name 'message' %}
                    <div class="form-group">
                        <label for="form-message">Email your Message</label>
                        <textarea class="common-input" id="id_message" name="message" placeholder="Message" rows="5"></textarea>
                    </div>
                    {% endifequal %}
                    {% for error in field.errors %}
                        <span class="error" id="field_errors">{{ error }}</span><br/>
                    {% endfor %}
                {% endfor %}
                <button class="btn btn-block genric-btn primary radius" type="submit" style="font-size: larger;">Contact Us</button>             
            </form>
        </div>
    </div>
</div>


{% endblock %}

{% block scripts %}
<script src="{% static 'js/accounts.js' %}"></script> 
<script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
    validate_email("#id_contact_email","#email_error");
    validate_name("#id_contact_name","#contact_error");
    jQuery(function ($) {
        // Google Maps setup
        var googlemap = new google.maps.Map(
            document.getElementById('googlemap'),
            {
                center: new google.maps.LatLng(21.082034, 72.5463),
                zoom: 8,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            }
        );
    });
</script>
{% endblock %}

shop/templates/forget_password.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load env_extras %}
{% block meta_tags %}
{% endblock %}

{% block title_tag %}{% get_site_setting as site %}{{ site.forget_page_title }}{% endblock %}

{% block custom_css_and_links %}

{% endblock %}

{% block breadcrum %}
<section class="banner-area organic-breadcrumb">
  <div class="container mt-lg-0 mt-md-120 mt-120 mt-sm-200">
      <div class="breadcrumb-banner d-flex flex-wrap align-items-center">
          <div class="col-lg-12 col-xs-12 col-first col-sm-12 d-flex flex-wrap align-items-center">
              <a href="{% url 'home'%}">Home&nbsp;&nbsp;<i class="fa fa-caret-right" aria-hidden="true"></i>&nbsp;</a>
              <a href="{% url 'accounts'%}">Accounts&nbsp;&nbsp;<i class="fa fa-caret-right" aria-hidden="true"></i>&nbsp;</a>
              <a href="{% url 'forget-password'%}">Forget Password</a>
          </div>
      </div>
  </div>
</section>
{% endblock %}

{% block content %}
<div class="container">
  <div class="container">
    <div class="row success-messages">
      {% if messages %}
        {% for message in messages %}
          {% if  message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <span class="text-center"><i class="fa fa-check-circle-o" aria-hidden="true"></i>&nbsp;&nbsp;{{message}}</span>
          {% endif %}
        {% endfor %}
      {% endif %}
    </div>
  </div>
  <div class="row account-form">
    <div class="col-md-12">
      <div class="login-form">
        <h3 class="billing-title text-center">Forget Password</h3>
        <p class="text-center mt-40 mb-30 account-sub-title">Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
        <form action="{% url 'forget-password' %}" method="POST">  
          {% csrf_token %}
          {% for field in form %}
              <label for="{{ field.name }}">{{ field.label }} <span class="error">*</span></label>
              {% ifequal field.name 'email' %}
                <input type="email" name="email" class="common-input mt-20" required="" id="id_email">
                <span class="error" id="email_error">
                    {% if email_error %}
                        {{email_error}}
                    {% endif %}
                    {% if user_not_exsist %}
                        {{user_not_exsist}}
                    {% endif %}
                </span>
              {% endifequal %}
              <p class="help-text">{{ field.help_text }} </p>
              {% for error in field.errors %}
                <span class="error" id="field_errors">{{ error }}</span><br/>
              {% endfor %}
          {% endfor %}
          <button type="submit" class="view-btn color-2 mt-20 w-100"><span>Send Email</span></button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}


{% block scripts %}
<script src="{% static 'js/accounts.js' %}"></script> 
<script>
    validate_email("#id_email","#email_error");
</script>
{% endblock %}

shop/templates/nav.html
{% load static %}
{% load mptt_tags %}
{% load env_extras %}
{% for node in category %}
    <a class="dropdown-item" href="{{node.get_absolute_url}}">{{node.title}}</a>
{% endfor %}